name: Flutter Build APK

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.x"  # Use latest stable version

      - name: Create Flutter project (if missing)
        run: |
          if [ ! -f "pubspec.yaml" ]; then
            flutter create .
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
